apiVersion: v2
name: o-neko
description: A Helm chart for O-Neko
type: application
version: 1.4.0
appVersion: "1.7.0"
sources:
- https://github.com/subshell/o-neko/
dependencies:
  - name: mongodb
    version: 13.6.7
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
